/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/face-scan`; params?: Router.UnknownInputParams; } | { pathname: `/face-setup`; params?: Router.UnknownInputParams; } | { pathname: `/identity-verification`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/relay-capture`; params?: Router.UnknownInputParams; } | { pathname: `/scan-qr`; params?: Router.UnknownInputParams; } | { pathname: `/setup-success`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/badge` | `/badge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/face-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/face-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/identity-verification`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/relay-capture`; params?: Router.UnknownOutputParams; } | { pathname: `/scan-qr`; params?: Router.UnknownOutputParams; } | { pathname: `/setup-success`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/badge` | `/badge`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/face-scan${`?${string}` | `#${string}` | ''}` | `/face-setup${`?${string}` | `#${string}` | ''}` | `/identity-verification${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/relay-capture${`?${string}` | `#${string}` | ''}` | `/scan-qr${`?${string}` | `#${string}` | ''}` | `/setup-success${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/badge${`?${string}` | `#${string}` | ''}` | `/badge${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/face-scan`; params?: Router.UnknownInputParams; } | { pathname: `/face-setup`; params?: Router.UnknownInputParams; } | { pathname: `/identity-verification`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/relay-capture`; params?: Router.UnknownInputParams; } | { pathname: `/scan-qr`; params?: Router.UnknownInputParams; } | { pathname: `/setup-success`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/badge` | `/badge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
